# Generated by Django 4.2.16 on 2024-09-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='content',
            field=models.TextField(),
        ),
    ]
